# Generated by Django 4.1.7 on 2024-02-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.DecimalField(decimal_places=0, max_digits=3)),
                ('gender', models.CharField(choices=[('муж', 'жен')], max_length=10)),
                ('date_in', models.DateField(auto_now=True)),
                ('sist_ad', models.DecimalField(decimal_places=0, max_digits=3)),
                ('diast_ad', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
    ]
