# Generated by Django 4.1.7 on 2024-02-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_chart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='gender',
            field=models.CharField(choices=[('gender1', 'муж'), ('gender2', 'жен')], max_length=10),
        ),
    ]
