# Generated by Django 4.1.7 on 2024-02-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_chart', '0002_alter_chart_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='gender',
            field=models.CharField(max_length=3),
        ),
    ]
