# Generated by Django 5.0.1 on 2024-02-18 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_chart', '0004_alter_chart_date_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='date_in',
            field=models.DateTimeField(default=datetime.datetime),
        ),
    ]
